"""
Convert a Supabase cluster backup (pg_dumpall output, optionally .gz) into SQL that
restores cleanly on Neon.

What is kept:
  - the `public` schema: enum type, tables, sequences, functions, trigger, indexes,
    constraints, and all rows
  - `auth.users` rows, copied into `public.auth_users` (bcrypt hashes are kept, so
    existing passwords keep working with the backend's own JWT auth)

What is dropped:
  - Supabase-only schemas (auth, storage, realtime, vault, graphql, ...), roles,
    grants, RLS toggles, and ownership statements
  - Supabase sessions and refresh tokens (they are signed with the Supabase JWT
    secret and cannot be carried over; users sign in again once)

Stored Supabase Storage URLs (course_contents.access_url, generated_materials
file_location/payload) are rewritten to STORAGE_PUBLIC_URL so they point at the
S3-compatible bucket populated by backend/scripts/migrate_supabase_storage.py.

Usage:
  python backend/database/neon/build_neon_migration.py ~/Downloads/db_cluster-....backup.gz \
    --storage-public-url https://files.example.com
  python backend/database/neon/build_neon_migration.py ~/Downloads/db_cluster-....backup.gz \
    --schema-only --output backend/database/neon/schema.sql

Restore (use the direct, non-pooled Neon connection string):
  psql "$DIRECT_URL" -v ON_ERROR_STOP=1 -f backend/database/neon/out/neon_restore.sql
"""

from __future__ import annotations

import argparse
import gzip
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path


DEFAULT_OUTPUT = Path(__file__).resolve().parent / "out" / "neon_restore.sql"
REPO_ENV_FILE = Path(__file__).resolve().parents[3] / ".env"

SCHEMA_BLOCK_TYPES = {
    "TYPE",
    "COMMENT",
    "FUNCTION",
    "TABLE",
    "SEQUENCE",
    "SEQUENCE OWNED BY",
    "DEFAULT",
    "CONSTRAINT",
    "INDEX",
    "TRIGGER",
    "FK CONSTRAINT",
}
DATA_BLOCK_TYPES = {"TABLE DATA", "SEQUENCE SET"}

BLOCK_HEADER = re.compile(
    r"^(?:Data for )?Name: (?P<name>.*?); Type: (?P<type>.*?); Schema: (?P<schema>.*?); Owner: .*?\n--\n"
)
OWNER_STATEMENT = re.compile(r"^ALTER [A-Z ]+ .* OWNER TO [^;]+;\n?", re.MULTILINE)
SUPABASE_OBJECT_URL = re.compile(
    r"https://[a-z0-9-]+\.supabase\.co/storage/v1/object/(?:public/)?[^/\s\"\\]+/"
)

AUTH_USERS_COLUMNS = (
    "id",
    "email",
    "encrypted_password",
    "raw_user_meta_data",
    "email_confirmed_at",
    "last_sign_in_at",
    "created_at",
    "updated_at",
    "deleted_at",
)

PREAMBLE = """\
-- Generated by backend/database/neon/build_neon_migration.py
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SELECT pg_catalog.set_config('search_path', '', false);

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
"""

AUTH_USERS_DDL = """\
--
-- Backend-owned auth (replaces Supabase auth.users)
--

CREATE TABLE public.auth_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    encrypted_password text NOT NULL,
    user_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    email_confirmed_at timestamp with time zone,
    last_sign_in_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT auth_users_pkey PRIMARY KEY (id),
    CONSTRAINT auth_users_email_lowercase_check CHECK (email = lower(email))
);

CREATE UNIQUE INDEX auth_users_email_key ON public.auth_users USING btree (email);
"""

AUTH_USERS_BACKFILL = """\
-- Users created before profile metadata was written to auth get it from public.users.
UPDATE public.auth_users AS auth_user
SET user_metadata = auth_user.user_metadata
    || jsonb_build_object('username', profile.username, 'profession', profile.profession::text)
FROM public.users AS profile
WHERE profile.user_uuid = auth_user.id
  AND NOT (auth_user.user_metadata ? 'username');
"""


@dataclass(frozen=True)
class DumpBlock:
    name: str
    type: str
    schema: str
    body: str


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("backup", type=Path, help="Supabase cluster backup (.backup, .sql, or .gz)")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--storage-public-url",
        default=None,
        help="Public base URL of the new bucket; replaces stored Supabase object URLs "
        "(default: STORAGE_PUBLIC_URL from the environment or the repo-root .env)",
    )
    parser.add_argument("--schema-only", action="store_true", help="Emit DDL without any rows")
    args = parser.parse_args()

    if not args.storage_public_url:
        args.storage_public_url = os.getenv("STORAGE_PUBLIC_URL") or _read_env_file_value("STORAGE_PUBLIC_URL")
    if not args.schema_only:
        if not args.storage_public_url:
            parser.error("--storage-public-url is required unless --schema-only is set")
        if not args.storage_public_url.startswith("https://") or "<" in args.storage_public_url:
            parser.error(f"--storage-public-url is not a real https URL: {args.storage_public_url}")

    dump_text = _read_dump(args.backup)
    blocks = _split_blocks(dump_text)
    sql, stats = _build_sql(
        blocks=blocks,
        dump_text=dump_text,
        schema_only=args.schema_only,
        storage_public_url=(args.storage_public_url or "").rstrip("/"),
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql)

    print(f"Wrote {args.output}")
    for label, value in stats.items():
        print(f"  {label}: {value}")
    return 0


def _read_env_file_value(name: str) -> str | None:
    if not REPO_ENV_FILE.exists():
        return None
    for line in REPO_ENV_FILE.read_text().splitlines():
        key, separator, value = line.partition("=")
        if separator and key.strip() == name:
            return value.strip().strip("\"'") or None
    return None


def _read_dump(path: Path) -> str:
    raw = path.read_bytes()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return raw.decode("utf-8")


def _split_blocks(dump_text: str) -> list[DumpBlock]:
    marker = "\\connect postgres"
    if marker not in dump_text:
        raise SystemExit("Backup does not contain the `postgres` database section.")

    database_section = dump_text[dump_text.index(marker):]
    blocks: list[DumpBlock] = []

    for chunk in re.split(r"\n--\n-- (?=(?:Data for )?Name: )", database_section)[1:]:
        header = BLOCK_HEADER.match(chunk)
        if not header:
            continue
        body = chunk[header.end():]
        # The next block's leading "--" comment line is not part of this body.
        body = re.sub(r"\n--\s*$", "\n", body)
        blocks.append(DumpBlock(header["name"], header["type"], header["schema"], body))

    return blocks


def _build_sql(
    *,
    blocks: list[DumpBlock],
    dump_text: str,
    schema_only: bool,
    storage_public_url: str,
) -> tuple[str, dict[str, int]]:
    parts = [PREAMBLE]
    stats = {"public blocks": 0, "rows": 0, "rewritten storage URLs": 0, "auth users": 0}
    kept_types = SCHEMA_BLOCK_TYPES if schema_only else SCHEMA_BLOCK_TYPES | DATA_BLOCK_TYPES

    for block in blocks:
        if block.schema != "public" or block.type not in kept_types:
            continue

        body = OWNER_STATEMENT.sub("", block.body)
        body = body.replace(" DEFAULT auth.uid()", "")
        if "auth." in body and block.type != "TABLE DATA":
            raise SystemExit(f"Unhandled Supabase auth reference in {block.type} {block.name}")

        if block.type == "TABLE DATA":
            stats["rows"] += _count_copy_rows(body)
            body, replaced = SUPABASE_OBJECT_URL.subn(f"{storage_public_url}/", body)
            stats["rewritten storage URLs"] += replaced

        parts.append(f"--\n-- {block.type}: {block.name}\n--\n{body.strip()}\n")
        stats["public blocks"] += 1

    parts.append(AUTH_USERS_DDL)
    if not schema_only:
        auth_copy, auth_user_count = _build_auth_users_copy(dump_text)
        parts.append(auth_copy)
        parts.append(AUTH_USERS_BACKFILL)
        stats["auth users"] = auth_user_count

    parts.append("COMMIT;\n")
    return "\n".join(parts), stats


def _count_copy_rows(body: str) -> int:
    lines = body.split("\n")
    start = next((index for index, line in enumerate(lines) if line.startswith("COPY ")), None)
    if start is None:
        return 0
    end = lines.index("\\.", start)
    return end - start - 1


def _build_auth_users_copy(dump_text: str) -> tuple[str, int]:
    lines = dump_text.split("\n")
    start = next(index for index, line in enumerate(lines) if line.startswith("COPY auth.users "))
    header = lines[start]
    source_columns = header[header.index("(") + 1:header.index(")")].split(", ")
    missing = [column for column in AUTH_USERS_COLUMNS if column not in source_columns]
    if missing:
        raise SystemExit(f"auth.users is missing expected columns: {', '.join(missing)}")

    output_rows: list[str] = []
    for line in lines[start + 1:]:
        if line == "\\.":
            break
        values = dict(zip(source_columns, line.split("\t")))
        if values.get("is_anonymous") == "t":
            continue

        row = [values[column] for column in AUTH_USERS_COLUMNS]
        row[1] = row[1].lower()
        if row[2] == "\\N":
            row[2] = ""
        if row[3] == "\\N":
            row[3] = "{}"
        output_rows.append("\t".join(row))

    target_columns = ", ".join(
        "user_metadata" if column == "raw_user_meta_data" else column for column in AUTH_USERS_COLUMNS
    )
    copy_sql = (
        f"COPY public.auth_users ({target_columns}) FROM stdin;\n"
        + "".join(f"{row}\n" for row in output_rows)
        + "\\.\n"
    )
    return copy_sql, len(output_rows)


if __name__ == "__main__":
    sys.exit(main())
