-- Generated by backend/database/neon/build_neon_migration.py
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SELECT pg_catalog.set_config('search_path', '', false);

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

--
-- TYPE: profession
--
CREATE TYPE public.profession AS ENUM (
    'professor',
    'student'
);

--
-- COMMENT: TYPE profession
--
COMMENT ON TYPE public.profession IS 'What role the user plays within an educational system';

--
-- FUNCTION: append_project_chat_exchange(bigint, text, jsonb, jsonb)
--
CREATE FUNCTION public.append_project_chat_exchange(filter_project_id bigint, filter_owner_user_id text, user_message jsonb, assistant_message jsonb) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
  project_owner_user_id text;
  current_messages jsonb;
  combined_messages jsonb;
  retained_messages jsonb;
BEGIN
  SELECT owner_user_id
  INTO project_owner_user_id
  FROM public.projects
  WHERE id = filter_project_id;

  IF project_owner_user_id IS NULL OR project_owner_user_id <> filter_owner_user_id THEN
    RAISE EXCEPTION 'Project was not found.';
  END IF;

  IF user_message->>'role' <> 'user'
     OR assistant_message->>'role' <> 'assistant' THEN
    RAISE EXCEPTION 'Chat exchange roles are invalid.';
  END IF;

  INSERT INTO public.project_chat_memory (project_id, owner_user_id)
  VALUES (filter_project_id, filter_owner_user_id)
  ON CONFLICT (project_id) DO NOTHING;

  SELECT messages
  INTO current_messages
  FROM public.project_chat_memory
  WHERE project_id = filter_project_id
    AND owner_user_id = filter_owner_user_id
  FOR UPDATE;

  IF current_messages IS NULL THEN
    RAISE EXCEPTION 'Chat memory was not found.';
  END IF;

  combined_messages :=
    current_messages || jsonb_build_array(user_message, assistant_message);

  SELECT COALESCE(jsonb_agg(item ORDER BY position), '[]'::jsonb)
  INTO retained_messages
  FROM jsonb_array_elements(combined_messages) WITH ORDINALITY AS entries(item, position)
  WHERE position > GREATEST(jsonb_array_length(combined_messages) - 10, 0);

  UPDATE public.project_chat_memory
  SET messages = retained_messages,
      updated_at = NOW()
  WHERE project_id = filter_project_id
    AND owner_user_id = filter_owner_user_id;

  RETURN retained_messages;
END;
$$;

--
-- FUNCTION: match_course_content_chunks(public.vector, bigint, integer, bigint)
--
CREATE FUNCTION public.match_course_content_chunks(query_embedding public.vector, filter_project_id bigint, match_count integer DEFAULT 8, filter_material_id bigint DEFAULT NULL::bigint) RETURNS TABLE(id bigint, project_id bigint, course_content_id bigint, material_name text, chunk_index integer, text text, start_char integer, end_char integer, location_kind text, location_start integer, location_end integer, similarity double precision)
    LANGUAGE sql STABLE
    AS $$
  SELECT
    chunk.id,
    chunk.project_id,
    chunk.course_content_id,
    chunk.material_name,
    chunk.chunk_index,
    chunk.text,
    chunk.start_char,
    chunk.end_char,
    chunk.location_kind,
    chunk.location_start,
    chunk.location_end,
    1 - (chunk.embedding <=> query_embedding) AS similarity
  FROM public.course_content_chunks AS chunk
  JOIN public.course_contents AS course_content
    ON course_content.id = chunk.course_content_id
  WHERE chunk.project_id = filter_project_id
    AND course_content.rag_status = 'ready'
    AND (filter_material_id IS NULL OR chunk.course_content_id = filter_material_id)
  ORDER BY chunk.embedding <=> query_embedding
  LIMIT match_count;
$$;

--
-- FUNCTION: projects_set_updated_at()
--
CREATE FUNCTION public.projects_set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

--
-- TABLE: users
--
CREATE TABLE public.users (
    id bigint NOT NULL,
    username text NOT NULL,
    profession public.profession NOT NULL,
    user_uuid uuid NOT NULL
);

--
-- SEQUENCE: User_id_seq
--
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TABLE: course_content_chunks
--
CREATE TABLE public.course_content_chunks (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    course_content_id bigint NOT NULL,
    material_name text NOT NULL,
    chunk_index integer NOT NULL,
    text text NOT NULL,
    start_char integer,
    end_char integer,
    embedding public.vector(768) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    location_kind text,
    location_start integer,
    location_end integer
);

--
-- SEQUENCE: course_content_chunks_id_seq
--
CREATE SEQUENCE public.course_content_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- SEQUENCE OWNED BY: course_content_chunks_id_seq
--
ALTER SEQUENCE public.course_content_chunks_id_seq OWNED BY public.course_content_chunks.id;

--
-- TABLE: course_contents
--
CREATE TABLE public.course_contents (
    id bigint NOT NULL,
    material_name character varying NOT NULL,
    access_url text,
    data_size bigint NOT NULL,
    project_uuid uuid,
    project_id bigint,
    content_sha256 text,
    rag_status text DEFAULT 'pending'::text,
    rag_chunk_count integer DEFAULT 0,
    rag_error text,
    CONSTRAINT course_contents_rag_status_check CHECK ((rag_status = ANY (ARRAY['pending'::text, 'ready'::text, 'failed'::text])))
);

--
-- SEQUENCE: course_content_id_seq
--
ALTER TABLE public.course_contents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TABLE: generated_materials
--
CREATE TABLE public.generated_materials (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    uuid uuid DEFAULT gen_random_uuid(),
    input_token bigint,
    output_token bigint,
    project_uuid uuid NOT NULL,
    name text,
    file_location text NOT NULL,
    tool_type text DEFAULT 'quiz'::text NOT NULL,
    source_material_ids bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL
);

--
-- SEQUENCE: generated_materials_id_seq
--
ALTER TABLE public.generated_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generated_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TABLE: project_chat_memory
--
CREATE TABLE public.project_chat_memory (
    project_id bigint NOT NULL,
    owner_user_id text NOT NULL,
    messages jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT project_chat_memory_messages_array_check CHECK ((jsonb_typeof(messages) = 'array'::text))
);

--
-- TABLE: project_materials
--
CREATE TABLE public.project_materials (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    project_id bigint,
    material_id bigint
);

--
-- TABLE: projects
--
CREATE TABLE public.projects (
    id bigint NOT NULL,
    name text NOT NULL,
    created_by text NOT NULL,
    created_on timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    owner_auth_user_id uuid,
    project_uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    owner_user_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

--
-- SEQUENCE: projects_id_seq
--
ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TABLE: user_projects
--
CREATE TABLE public.user_projects (
    user_id bigint NOT NULL,
    project_id bigint NOT NULL
);

--
-- COMMENT: TABLE user_projects
--
COMMENT ON TABLE public.user_projects IS 'Join table where user are associated with different projects';

--
-- DEFAULT: course_content_chunks id
--
ALTER TABLE ONLY public.course_content_chunks ALTER COLUMN id SET DEFAULT nextval('public.course_content_chunks_id_seq'::regclass);

--
-- CONSTRAINT: users User_pkey
--
ALTER TABLE ONLY public.users
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (id);

--
-- CONSTRAINT: users User_username_key
--
ALTER TABLE ONLY public.users
    ADD CONSTRAINT "User_username_key" UNIQUE (username);

--
-- CONSTRAINT: course_content_chunks course_content_chunks_course_content_id_chunk_index_key
--
ALTER TABLE ONLY public.course_content_chunks
    ADD CONSTRAINT course_content_chunks_course_content_id_chunk_index_key UNIQUE (course_content_id, chunk_index);

--
-- CONSTRAINT: course_content_chunks course_content_chunks_pkey
--
ALTER TABLE ONLY public.course_content_chunks
    ADD CONSTRAINT course_content_chunks_pkey PRIMARY KEY (id);

--
-- CONSTRAINT: course_contents course_content_pkey
--
ALTER TABLE ONLY public.course_contents
    ADD CONSTRAINT course_content_pkey PRIMARY KEY (id);

--
-- CONSTRAINT: generated_materials generated_materials_pkey
--
ALTER TABLE ONLY public.generated_materials
    ADD CONSTRAINT generated_materials_pkey PRIMARY KEY (id);

--
-- CONSTRAINT: generated_materials generated_materials_uuid_key
--
ALTER TABLE ONLY public.generated_materials
    ADD CONSTRAINT generated_materials_uuid_key UNIQUE (uuid);

--
-- CONSTRAINT: project_chat_memory project_chat_memory_pkey
--
ALTER TABLE ONLY public.project_chat_memory
    ADD CONSTRAINT project_chat_memory_pkey PRIMARY KEY (project_id);

--
-- CONSTRAINT: projects projects_pkey
--
ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

--
-- CONSTRAINT: projects projects_project_uuid_key
--
ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_project_uuid_key UNIQUE (project_uuid);

--
-- CONSTRAINT: user_projects user_materials_pkey
--
ALTER TABLE ONLY public.user_projects
    ADD CONSTRAINT user_materials_pkey PRIMARY KEY (user_id, project_id);

--
-- INDEX: idx_course_content_chunks_course_content_id
--
CREATE INDEX idx_course_content_chunks_course_content_id ON public.course_content_chunks USING btree (course_content_id);

--
-- INDEX: idx_course_content_chunks_embedding_ivfflat
--
CREATE INDEX idx_course_content_chunks_embedding_ivfflat ON public.course_content_chunks USING ivfflat (embedding public.vector_cosine_ops) WITH (lists='100');

--
-- INDEX: idx_course_content_chunks_project_id
--
CREATE INDEX idx_course_content_chunks_project_id ON public.course_content_chunks USING btree (project_id);

--
-- INDEX: idx_course_contents_project_content_sha256_unique
--
CREATE UNIQUE INDEX idx_course_contents_project_content_sha256_unique ON public.course_contents USING btree (project_id, content_sha256) WHERE ((project_id IS NOT NULL) AND (content_sha256 IS NOT NULL));

--
-- INDEX: idx_course_contents_project_rag_status
--
CREATE INDEX idx_course_contents_project_rag_status ON public.course_contents USING btree (project_id, rag_status);

--
-- INDEX: idx_generated_materials_project_tool_created_at
--
CREATE INDEX idx_generated_materials_project_tool_created_at ON public.generated_materials USING btree (project_uuid, tool_type, created_at DESC);

--
-- INDEX: idx_generated_materials_source_material_ids_gin
--
CREATE INDEX idx_generated_materials_source_material_ids_gin ON public.generated_materials USING gin (source_material_ids);

--
-- INDEX: idx_project_chat_memory_owner_user_id
--
CREATE INDEX idx_project_chat_memory_owner_user_id ON public.project_chat_memory USING btree (owner_user_id);

--
-- INDEX: idx_projects_owner_user_id
--
CREATE INDEX idx_projects_owner_user_id ON public.projects USING btree (owner_user_id);

--
-- INDEX: projects_owner_auth_user_id_created_on_idx
--
CREATE INDEX projects_owner_auth_user_id_created_on_idx ON public.projects USING btree (owner_auth_user_id, created_on DESC, id DESC);

--
-- TRIGGER: projects trg_projects_set_updated_at
--
CREATE TRIGGER trg_projects_set_updated_at BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION public.projects_set_updated_at();

--
-- FK CONSTRAINT: course_content_chunks course_content_chunks_course_content_id_fkey
--
ALTER TABLE ONLY public.course_content_chunks
    ADD CONSTRAINT course_content_chunks_course_content_id_fkey FOREIGN KEY (course_content_id) REFERENCES public.course_contents(id) ON DELETE CASCADE;

--
-- FK CONSTRAINT: course_contents course_contents_project_uuid_fkey
--
ALTER TABLE ONLY public.course_contents
    ADD CONSTRAINT course_contents_project_uuid_fkey FOREIGN KEY (project_uuid) REFERENCES public.projects(project_uuid);

--
-- FK CONSTRAINT: generated_materials generated_materials_project_uuid_fkey
--
ALTER TABLE ONLY public.generated_materials
    ADD CONSTRAINT generated_materials_project_uuid_fkey FOREIGN KEY (project_uuid) REFERENCES public.projects(project_uuid) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- FK CONSTRAINT: project_chat_memory project_chat_memory_project_id_fkey
--
ALTER TABLE ONLY public.project_chat_memory
    ADD CONSTRAINT project_chat_memory_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

--
-- FK CONSTRAINT: project_materials project_materials_material_id_fkey
--
ALTER TABLE ONLY public.project_materials
    ADD CONSTRAINT project_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.course_contents(id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- FK CONSTRAINT: project_materials project_materials_project_id_fkey
--
ALTER TABLE ONLY public.project_materials
    ADD CONSTRAINT project_materials_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id);

--
-- FK CONSTRAINT: user_projects user_materials_project_id_fkey
--
ALTER TABLE ONLY public.user_projects
    ADD CONSTRAINT user_materials_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- FK CONSTRAINT: user_projects user_materials_user_id_fkey
--
ALTER TABLE ONLY public.user_projects
    ADD CONSTRAINT user_materials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Backend-owned auth (replaces Supabase auth.users)
--

CREATE TABLE public.auth_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    encrypted_password text NOT NULL,
    user_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    email_confirmed_at timestamp with time zone,
    last_sign_in_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT auth_users_pkey PRIMARY KEY (id),
    CONSTRAINT auth_users_email_lowercase_check CHECK (email = lower(email))
);

CREATE UNIQUE INDEX auth_users_email_key ON public.auth_users USING btree (email);

COMMIT;
